version: '3'

services:
  jakarta-db:
    container_name: jakarta-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tzkt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwerty}
      POSTGRES_DB: ${POSTGRES_DB:-tzkt_db}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5434:5432

  jakarta-api:
    container_name: jakarta-api
    restart: always
    image: bakingbad/tzkt-api:latest
    depends_on:
      - jakarta-db
    environment:
      ConnectionStrings__DefaultConnection: host=jakarta-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
      Kestrel__Endpoints__Http__Url: http://0.0.0.0:5000
    ports:
      - 0.0.0.0:5020:5000

  jakarta-sync:
    container_name: jakarta-sync
    restart: always
    image: bakingbad/tzkt-sync:latest
    environment:
      ConnectionStrings__DefaultConnection: host=jakarta-db;port=5432;database=${POSTGRES_DB:-tzkt_db};username=${POSTGRES_USER:-tzkt};password=${POSTGRES_PASSWORD:-qwerty};
      TezosNode__Endpoint: https://rpc.tzkt.io/jakartanet/
    depends_on:
      - jakarta-db

volumes:
  postgres:
